require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

  Exclude:
    # FIXME: Remove lines below when https://github.com/nevir/rubocop-rspec/issues/62 is fixed
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/bin/**/*'

Metrics/AbcSize:
  Max: 25
